### PR TITLE
set baseURL for text2vec-openai schema config

### LINKED ISSUE #147: Feat: Add baseURL config for Weaviate schema generation
The generated schema doesn't seem to have an option to configure a base URL:
baseURL	string	Optional	https://api.openai.com	Sets a proxy or other URL instead of the default OpenAI URL.

Use a the protocol domain format: https://your.domain.com.

Currently you can only set the OPENAI base url for the LLM calls that Verba makes but the schemas generated by Verba do not correctly set the base URL.

### PR DESCRIPTION
**Pull request by samos123**
Fixes #147

### CODE REVIEW

**Comment by samos123** [comment]
Some baseURLs are still not being set correctly:
```
{
  "classes": [
    {
      "class": "Document_text2vec_cohere",
      "description": "Documentation",
      "invertedIndexConfig": {
        "bm25": {
          "b": 0.75,
          "k1": 1.2
        },
        "cleanupIntervalSeconds": 60,
        "stopwords": {
          "additions": null,
          "preset": "en",
          "removals": null
        }
      },
      "multiTenancyConfig": {
        "enabled": false
      },
      "properties": [
        {
          "dataType": [
            "text"
          ],
          "description": "Content of the document",
          "indexFilterable": true,
          "indexSearchable": true,
          "name": "text",
          "tokenization": "word"
        },
        {
          "dataType": [
            "text"
          ],
          "description": "Document name",
          "indexFilterable": true,
          "indexSearchable": true,
          "name": "doc_name",
          "tokenization": "word"
        },
        {
          "dataType": [
            "text"
          ],
          "description": "Document type",
          "indexFilterable": true,
          "indexSearchable": true,
          "name": "doc_type",
          "tokenization": "word"
        },
        {
          "dataType": [
            "text"
          ],
          "description": "Link to document",
          "indexFilterable": true,
          "indexSearchable": true,
          "name": "doc_link",
          "tokenization": "word"
        },
        {
          "dataType": [
            "text"
          ],
          "description": "Timestamp of document",
          "indexFilterable": true,
          "indexSearchable": true,
          "name": "timestamp",
          "tokenization": "word"
        },
        {
          "dataType": [
            "number"
          ],
          "description": "Number of chunks",
          "indexFilterable": true,
          "indexSearchable": false,
          "name": "chunk_count"
        }
      ],
      "replicationConfig": {
        "factor": 1
      },
      "shardingConfig": {
        "virtualPerPhysical": 128,
        "desiredCount": 1,
        "actualCount": 1,
        "desiredVirtualCount": 128,
        "actualVirtualCount": 128,
        "key": "_id",
        "strategy": "hash",
        "function": "murmur3"
      },
      "vectorIndexConfig": {
        "skip": false,
        "cleanupIntervalSeconds": 300,
        "maxConnections": 64,
        "efConstruction": 128,
        "ef": -1,
        "dynamicEfMin": 100,
        "dynamicEfMax": 500,
        "dynamicEfFactor": 8,
        "vectorCacheMaxObjects": 1000000000000,
        "flatSearchCutoff": 40000,
        "distance": "cosine",
        "pq": {
          "enabled": false,
          "bitCompression": false,
          "segments": 0,
          "centroids": 256,
          "trainingLimit": 100000,
          "encoder": {
            "type": "kmeans",
            "distribution": "log-normal"
          }
        },
        "bq": {
          "enabled": false
        }
      },
      "vectorIndexType": "hnsw",
      "vectorizer": "none"
    },
    {
      "class": "Document_text2vec_openai",
      "description": "Documentation",
      "invertedIndexConfig": {
        "bm25": {
          "b": 0.75,
          "k1": 1.2
        },
        "cleanupIntervalSeconds": 60,
        "stopwords": {
          "additions": null,
          "preset": "en",
          "removals": null
        }
      },
      "multiTenancyConfig": {
        "enabled": false
      },
      "properties": [
        {
          "dataType": [
            "text"
          ],
          "description": "Content of the document",
          "indexFilterable": true,
          "indexSearchable": true,
          "name": "text",
          "tokenization": "word"
        },
        {
          "dataType": [
            "text"
          ],
          "description": "Document name",
          "indexFilterable": true,
          "indexSearchable": true,
          "name": "doc_name",
          "tokenization": "word"
        },
        {
          "dataType": [
            "text"
          ],
          "description": "Document type",
          "indexFilterable": true,
          "indexSearchable": true,
          "name": "doc_type",
          "tokenization": "word"
        },
        {
          "dataType": [
            "text"
          ],
          "description": "Link to document",
          "indexFilterable": true,
          "indexSearchable": true,
          "name": "doc_link",
          "tokenization": "word"
        },
        {
          "dataType": [
            "text"
          ],
          "description": "Timestamp of document",
          "indexFilterable": true,
          "indexSearchable": true,
          "name": "timestamp",
          "tokenization": "word"
        },
        {
          "dataType": [
            "number"
          ],
          "description": "Number of chunks",
          "indexFilterable": true,
          "indexSearchable": false,
          "name": "chunk_count"
        }
      ],
      "replicationConfig": {
        "factor": 1
      },
      "shardingConfig": {
        "virtualPerPhysical": 128,
        "desiredCount": 1,
        "actualCount": 1,
        "desiredVirtualCount": 128,
        "actualVirtualCount": 128,
        "key": "_id",
        "strategy": "hash",
        "function": "murmur3"
      },
      "vectorIndexConfig": {
        "skip": false,
        "cleanupIntervalSeconds": 300,
        "maxConnections": 64,
        "efConstruction": 128,
        "ef": -1,
        "dynamicEfMin": 100,
        "dynamicEfMax": 500,
        "dynamicEfFactor": 8,
        "vectorCacheMaxObjects": 1000000000000,
        "flatSearchCutoff": 40000,
        "distance": "cosine",
        "pq": {
          "enabled": false,
          "bitCompression": false,
          "segments": 0,
          "centroids": 256,
          "trainingLimit": 100000,
          "encoder": {
            "type": "kmeans",
            "distribution": "log-normal"
          }
        },
        "bq": {
          "enabled": false
        }
      },
      "vectorIndexType": "hnsw",
      "vectorizer": "none"
    },
    {
      "class": "Chunk_text2vec_openai",
      "description": "Chunks of Documentations",
      "invertedIndexConfig": {
        "bm25": {
          "b": 0.75,
          "k1": 1.2
        },
        "cleanupIntervalSeconds": 60,
        "stopwords": {
          "additions": null,
          "preset": "en",
          "removals": null
        }
      },
      "moduleConfig": {
        "text2vec-openai": {
          "baseURL": "https://api.openai.com",
          "model": "ada",
          "vectorizeClassName": true
        }
      },
      "multiTenancyConfig": {
        "enabled": false
      },
      "properties": [
        {
          "dataType": [
            "text"
          ],
          "description": "Content of the document",
          "indexFilterable": true,
          "indexSearchable": true,
          "moduleConfig": {
            "text2vec-openai": {
              "skip": false,
              "vectorizePropertyName": false
            }
          },
          "name": "text",
          "tokenization": "word"
        },
        {
          "dataType": [
            "text"
          ],
          "description": "Document name",
          "indexFilterable": true,
          "indexSearchable": true,
          "moduleConfig": {
            "text2vec-openai": {
              "skip": false,
              "vectorizePropertyName": false
            }
          },
          "name": "doc_name",
          "tokenization": "word"
        },
        {
          "dataType": [
            "text"
          ],
          "description": "Document type",
          "indexFilterable": true,
          "indexSearchable": true,
          "moduleConfig": {
            "text2vec-openai": {
              "baseURL": "http://lingo/v1",
              "skip": true,
              "vectorizePropertyName": false
            }
          },
          "name": "doc_type",
          "tokenization": "word"
        },
        {
          "dataType": [
            "text"
          ],
          "description": "Document UUID",
          "indexFilterable": true,
          "indexSearchable": true,
          "moduleConfig": {
            "text2vec-openai": {
              "baseURL": "http://lingo/v1",
              "skip": true,
              "vectorizePropertyName": false
            }
          },
          "name": "doc_uuid",
          "tokenization": "word"
        },
        {
          "dataType": [
            "number"
          ],
          "description": "Document chunk from the whole document",
          "indexFilterable": true,
          "indexSearchable": false,
          "moduleConfig": {
            "text2vec-openai": {
              "baseURL": "http://lingo/v1",
              "skip": true,
              "vectorizePropertyName": false
            }
          },
          "name": "chunk_id"
        }
      ],
      "replicationConfig": {
        "factor": 1
      },
      "shardingConfig": {
        "virtualPerPhysical": 128,
        "desiredCount": 1,
        "actualCount": 1,
        "desiredVirtualCount": 128,
        "actualVirtualCount": 128,
        "key": "_id",
        "strategy": "hash",
        "function": "murmur3"
      },
      "vectorIndexConfig": {
        "skip": false,
        "cleanupIntervalSeconds": 300,
        "maxConnections": 64,
        "efConstruction": 128,
        "ef": -1,
        "dynamicEfMin": 100,
        "dynamicEfMax": 500,
        "dynamicEfFactor": 8,
        "vectorCacheMaxObjects": 1000000000000,
        "flatSearchCutoff": 40000,
        "distance": "cosine",
        "pq": {
          "enabled": false,
          "bitCompression": false,
          "segments": 0,
          "centroids": 256,
          "trainingLimit": 100000,
          "encoder": {
            "type": "kmeans",
            "distribution": "log-normal"
          }
        },
        "bq": {
          "enabled": false
        }
      },
      "vectorIndexType": "hnsw",
      "vectorizer": "text2vec-openai"
    },
    {
      "class": "Cache_text2vec_openai",
      "description": "Cache of Documentations and their queries",
      "invertedIndexConfig": {
        "bm25": {
          "b": 0.75,
          "k1": 1.2
        },
        "cleanupIntervalSeconds": 60,
        "stopwords": {
          "additions": null,
          "preset": "en",
          "removals": null
        }
      },
      "moduleConfig": {
        "text2vec-openai": {
          "baseURL": "https://api.openai.com",
          "model": "ada",
          "vectorizeClassName": true
        }
      },
      "multiTenancyConfig": {
        "enabled": false
      },
      "properties": [
        {
          "dataType": [
            "text"
          ],
          "description": "Query",
          "indexFilterable": true,
          "indexSearchable": true,
          "moduleConfig": {
            "text2vec-openai": {
              "skip": false,
              "vectorizePropertyName": false
            }
          },
          "name": "query",
          "tokenization": "word"
        },
        {
          "dataType": [
            "text"
          ],
          "description": "System message",
          "indexFilterable": true,
          "indexSearchable": true,
          "moduleConfig": {
            "text2vec-openai": {
              "baseURL": "http://lingo/v1",
              "skip": true,
              "vectorizePropertyName": false
            }
          },
          "name": "system",
          "tokenization": "word"
        }
      ],
      "replicationConfig": {
        "factor": 1
      },
      "shardingConfig": {
        "virtualPerPhysical": 128,
        "desiredCount": 1,
        "actualCount": 1,
        "desiredVirtualCount": 128,
        "actualVirtualCount": 128,
        "key": "_id",
        "strategy": "hash",
        "function": "murmur3"
      },
      "vectorIndexConfig": {
        "skip": false,
        "cleanupIntervalSeconds": 300,
        "maxConnections": 64,
        "efConstruction": 128,
        "ef": -1,
        "dynamicEfMin": 100,
        "dynamicEfMax": 500,
        "dynamicEfFactor": 8,
        "vectorCacheMaxObjects": 1000000000000,
        "flatSearchCutoff": 40000,
        "distance": "cosine",
        "pq": {
          "enabled": false,
          "bitCompression": false,
          "segments": 0,
          "centroids": 256,
          "trainingLimit": 100000,
          "encoder": {
            "type": "kmeans",
            "distribution": "log-normal"
          }
        },
        "bq": {
          "enabled": false
        }
      },
      "vectorIndexType": "hnsw",
      "vectorizer": "text2vec-openai"
    },
    {
      "class": "Suggestion",
      "description": "List of possible prompts",
      "invertedIndexConfig": {
        "bm25": {
          "b": 0.75,
          "k1": 1.2
        },
        "cleanupIntervalSeconds": 60,
        "stopwords": {
          "additions": null,
          "preset": "en",
          "removals": null
        }
      },
      "multiTenancyConfig": {
        "enabled": false
      },
      "properties": [
        {
          "dataType": [
            "text"
          ],
          "description": "Query",
          "indexFilterable": true,
          "indexSearchable": true,
          "name": "suggestion",
          "tokenization": "word"
        }
      ],
      "replicationConfig": {
        "factor": 1
      },
      "shardingConfig": {
        "virtualPerPhysical": 128,
        "desiredCount": 1,
        "actualCount": 1,
        "desiredVirtualCount": 128,
        "actualVirtualCount": 128,
        "key": "_id",
        "strategy": "hash",
        "function": "murmur3"
      },
      "vectorIndexConfig": {
        "skip": false,
        "cleanupIntervalSeconds": 300,
        "maxConnections": 64,
        "efConstruction": 128,
        "ef": -1,
        "dynamicEfMin": 100,
        "dynamicEfMax": 500,
        "dynamicEfFactor": 8,
        "vectorCacheMaxObjects": 1000000000000,
        "flatSearchCutoff": 40000,
        "distance": "cosine",
        "pq": {
          "enabled": false,
          "bitCompression": false,
          "segments": 0,
          "centroids": 256,
          "trainingLimit": 100000,
          "encoder": {
            "type": "kmeans",
            "distribution": "log-normal"
          }
        },
        "bq": {
          "enabled": false
        }
      },
      "vectorIndexType": "hnsw",
      "vectorizer": "none"
    },
    {
      "class": "Document_MiniLM",
      "description": "Documentation",
      "invertedIndexConfig": {
        "bm25": {
          "b": 0.75,
          "k1": 1.2
        },
        "cleanupIntervalSeconds": 60,
        "stopwords": {
          "additions": null,
          "preset": "en",
          "removals": null
        }
      },
      "multiTenancyConfig": {
        "enabled": false
      },
      "properties": [
        {
          "dataType": [
            "text"
          ],
          "description": "Content of the document",
          "indexFilterable": true,
          "indexSearchable": true,
          "name": "text",
          "tokenization": "word"
        },
        {
          "dataType": [
            "text"
          ],
          "description": "Document name",
          "indexFilterable": true,
          "indexSearchable": true,
          "name": "doc_name",
          "tokenization": "word"
        },
        {
          "dataType": [
            "text"
          ],
          "description": "Document type",
          "indexFilterable": true,
          "indexSearchable": true,
          "name": "doc_type",
          "tokenization": "word"
        },
        {
          "dataType": [
            "text"
          ],
          "description": "Link to document",
          "indexFilterable": true,
          "indexSearchable": true,
          "name": "doc_link",
          "tokenization": "word"
        },
        {
          "dataType": [
            "text"
          ],
          "description": "Timestamp of document",
          "indexFilterable": true,
          "indexSearchable": true,
          "name": "timestamp",
          "tokenization": "word"
        },
        {
          "dataType": [
            "number"
          ],
          "description": "Number of chunks",
          "indexFilterable": true,
          "indexSearchable": false,
          "name": "chunk_count"
        }
      ],
      "replicationConfig": {
        "factor": 1
      },
      "shardingConfig": {
        "virtualPerPhysical": 128,
        "desiredCount": 1,
        "actualCount": 1,
        "desiredVirtualCount": 128,
        "actualVirtualCount": 128,
        "key": "_id",
        "strategy": "hash",
        "function": "murmur3"
      },
      "vectorIndexConfig": {
        "skip": false,
        "cleanupIntervalSeconds": 300,
        "maxConnections": 64,
        "efConstruction": 128,
        "ef": -1,
        "dynamicEfMin": 100,
        "dynamicEfMax": 500,
        "dynamicEfFactor": 8,
        "vectorCacheMaxObjects": 1000000000000,
        "flatSearchCutoff": 40000,
        "distance": "cosine",
        "pq": {
          "enabled": false,
          "bitCompression": false,
          "segments": 0,
          "centroids": 256,
          "trainingLimit": 100000,
          "encoder": {
            "type": "kmeans",
            "distribution": "log-normal"
          }
        },
        "bq": {
          "enabled": false
        }
      },
      "vectorIndexType": "hnsw",
      "vectorizer": "none"
    },
    {
      "class": "Chunk_MiniLM",
      "description": "Chunks of Documentations",
      "invertedIndexConfig": {
        "bm25": {
          "b": 0.75,
          "k1": 1.2
        },
        "cleanupIntervalSeconds": 60,
        "stopwords": {
          "additions": null,
          "preset": "en",
          "removals": null
        }
      },
      "multiTenancyConfig": {
        "enabled": false
      },
      "properties": [
        {
          "dataType": [
            "text"
          ],
          "description": "Content of the document",
          "indexFilterable": true,
          "indexSearchable": true,
          "name": "text",
          "tokenization": "word"
        },
        {
          "dataType": [
            "text"
          ],
          "description": "Document name",
          "indexFilterable": true,
          "indexSearchable": true,
          "name": "doc_name",
          "tokenization": "word"
        },
        {
          "dataType": [
            "text"
          ],
          "description": "Document type",
          "indexFilterable": true,
          "indexSearchable": true,
          "name": "doc_type",
          "tokenization": "word"
        },
        {
          "dataType": [
            "text"
          ],
          "description": "Document UUID",
          "indexFilterable": true,
          "indexSearchable": true,
          "name": "doc_uuid",
          "tokenization": "word"
        },
        {
          "dataType": [
            "number"
          ],
          "description": "Document chunk from the whole document",
          "indexFilterable": true,
          "indexSearchable": false,
          "name": "chunk_id"
        }
      ],
      "replicationConfig": {
        "factor": 1
      },
      "shardingConfig": {
        "virtualPerPhysical": 128,
        "desiredCount": 1,
        "actualCount": 1,
        "desiredVirtualCount": 128,
        "actualVirtualCount": 128,
        "key": "_id",
        "strategy": "hash",
        "function": "murmur3"
      },
      "vectorIndexConfig": {
        "skip": false,
        "cleanupIntervalSeconds": 300,
        "maxConnections": 64,
        "efConstruction": 128,
        "ef": -1,
        "dynamicEfMin": 100,
        "dynamicEfMax": 500,
        "dynamicEfFactor": 8,
        "vectorCacheMaxObjects": 1000000000000,
        "flatSearchCutoff": 40000,
        "distance": "cosine",
        "pq": {
          "enabled": false,
          "bitCompression": false,
          "segments": 0,
          "centroids": 256,
          "trainingLimit": 100000,
          "encoder": {
            "type": "kmeans",
            "distribution": "log-normal"
          }
        },
        "bq": {
          "enabled": false
        }
      },
      "vectorIndexType": "hnsw",
      "vectorizer": "none"
    },
    {
      "class": "Cache_MiniLM",
      "description": "Cache of Documentations and their queries",
      "invertedIndexConfig": {
        "bm25": {
          "b": 0.75,
          "k1": 1.2
        },
        "cleanupIntervalSeconds": 60,
        "stopwords": {
          "additions": null,
          "preset": "en",
          "removals": null
        }
      },
      "multiTenancyConfig": {
        "enabled": false
      },
      "properties": [
        {
          "dataType": [
            "text"
          ],
          "description": "Query",
          "indexFilterable": true,
          "indexSearchable": true,
          "name": "query",
          "tokenization": "word"
        },
        {
          "dataType": [
            "text"
          ],
          "description": "System message",
          "indexFilterable": true,
          "indexSearchable": true,
          "name": "system",
          "tokenization": "word"
        }
      ],
      "replicationConfig": {
        "factor": 1
      },
      "shardingConfig": {
        "virtualPerPhysical": 128,
        "desiredCount": 1,
        "actualCount": 1,
        "desiredVirtualCount": 128,
        "actualVirtualCount": 128,
        "key": "_id",
        "strategy": "hash",
        "function": "murmur3"
      },
      "vectorIndexConfig": {
        "skip": false,
        "cleanupIntervalSeconds": 300,
        "maxConnections": 64,
        "efConstruction": 128,
        "ef": -1,
        "dynamicEfMin": 100,
        "dynamicEfMax": 500,
        "dynamicEfFactor": 8,
        "vectorCacheMaxObjects": 1000000000000,
        "flatSearchCutoff": 40000,
        "distance": "cosine",
        "pq": {
          "enabled": false,
          "bitCompression": false,
          "segments": 0,
          "centroids": 256,
          "trainingLimit": 100000,
          "encoder": {
            "type": "kmeans",
            "distribution": "log-normal"
          }
        },
        "bq": {
          "enabled": false
        }
      },
      "vectorIndexType": "hnsw",
      "vectorizer": "none"
    }
  ]
}
```

Note sure where my code is wrong

**Comment by samos123** [comment]
nvm it's working now. Could use a review on this.

**Comment by thomashacker** [comment]
Thanks for the PR 🚀 I'll have a look

**Review by thomashacker — APPROVED** [review]
Looks good to me, thanks a lot!

**Pull request merged**
