### PR TITLE
Remove Unnececary imports

### PR DESCRIPTION
**Pull request by umarmnaq**

### CODE REVIEW

**Comment by umarmnaq** [comment]
I agree to the CLA

**Comment by umarmnaq** [comment]
I agree to the CLA

**Comment by thomashacker** [comment]
Thanks for the `PR`, we're currently refactoring the codebase, and the new version will be published in the next few weeks! These imports will likely be removed in the new version

**Comment by thomashacker** [comment]
Thanks a lot for your `PR`! We just merged the new code refactor which fixes this bug 🚀  I'll close this PR

**Pull request closed without merging**
