### PR TITLE
fix: enabled loading of utf-16-le encoded files in load_file and load_directory

### PR DESCRIPTION
**Pull request by thompsonson**
A small fix to enable the loading of utf-16-le encoded files. 

Not massively elegant as it only covers utf-16-le and utf-8. 

I think supporting more is bigger than a simple fix and requires more though.

### CODE REVIEW

**Comment by thompsonson** [comment]
I agree to the CLA

**Comment by thomashacker** [comment]
This is great, thanks for the PR! We're currently working on shipping the 0.3.0 version which has some big architecture changes, we'll come back to your fix once it's released!

**Comment by thomashacker** [comment]
Hey! We just merged the new version of Verba with the refactored code. If you like, you can update your changes to the new code! We also added a contribution guideline which I recommend to read 🚀  Thanks a lot!

**Comment by thomashacker** [comment]
Will close this PR for now, feel free to create a new PR!  🚀

**Pull request closed without merging**
