### PR TITLE
Update documentation as per issue #251

### PR DESCRIPTION
**Pull request by rugveddarwhekar**
Updated readme documentation as per the suggested change mentioned at https://github.com/weaviate/Verba/issues/251

### CODE REVIEW

**Review by rickystanley76 — APPROVED** [review]

**Review by rickystanley76 — APPROVED** [review]

**Review by rickystanley76 — APPROVED** [review]
Yes, I agree 👍

**Comment by rugveddarwhekar** [comment]
I agree with the CLA

**Review by rickystanley76 — APPROVED** [review]
I agree with the CLA

**Review by thomashacker — APPROVED** [review]
Looks good to me, thanks a lot 🚀

**Pull request merged**
