### PR TITLE
add infinity

### PR DESCRIPTION
**Pull request by michaelfeil**
Hey Weaviate,

I am adding infinity, with some design ideas.

With infinity, you can run any embedding model from MTEB (nomic, jina, baai, mistral). It patches the use of FA2, and dynamic batching under the hood. You can also run embedding quantization.

### CODE REVIEW

**Comment by michaelfeil** [comment]
@thomashacker Ready for review!

**Comment by thomashacker** [comment]
Thanks for the PR! We'll have a look 🚀

**Comment by michaelfeil** [comment]
@thomashacker Hey Edward, do you have an estimate how long the review takes? Getting hard to remember what I originally submitted as PR by now :)

**Comment by thomashacker** [comment]
Hey @michaelfeil , sorry, no estimation yet...

We're currently working on refactoring the backend and updating the Weaviate client. I'll come back to you once we finished it 🚀

**Comment by thomashacker** [comment]
We released the new v2 update! If you're still interested you can update your PR to the newest changes

**Comment by thomashacker** [comment]
Closing for now 😄

**Comment by michaelfeil** [comment]
@thomashacker Yeah, initial review took to long.

**Pull request closed without merging**
